# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myResourceGroupInBrazil-arm'
    subscriptionId: '106a7d32-8588-4894-b457-2adeba8dee84'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myResourceGroupInBrazil'
    location: 'Brazil South'
    templateLocation: 'Linked artifact'
    overrideParameters: '-projectName yurifrnm -linkedTemplateUri https://raw.githubusercontent.com/yurifranconeri/arm-template/master/CreateWebApp/get-started-deployment/linked-template/linkedStorageAccount.json'
    deploymentMode: 'Incremental'